name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.1"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Get GitHub Actions IP
        id: ip
        uses: candidob/get-runner-ip@v1.0.0

      - name: Setting environment variables
        run: |
          echo "AWS_DEFAULT_REGION=ap-southeast-2" >> $GITHUB_ENV
          echo "AWS_SG_NAME=launch-wizard-1" >> $GITHUB_ENV
          echo "GITHUB_ACTIONS_IP=${{ steps.ip.outputs.ipv4 }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Add GitHub Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ env.GITHUB_ACTIONS_IP }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2

      - name: Pull latest code
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          command: |
            cd /local/portfolio/
            sudo git pull origin main

      - name: Install npm dependencies
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          command: |
            cd /local/portfolio/
            sudo npm install

      - name: Build project
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          command: |
            cd /local/portfolio/
            sudo npm run build

      - name: Restart Nginx
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          command: sudo systemctl restart nginx

      - name: Remove GitHub Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ env.GITHUB_ACTIONS_IP }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
